### ISSUE TITLE
Disponible pour symfony 3.1.*

### ISSUE THREAD

**Issue by MWJordanP** [bnbc/Symfony-Upload-Ajax#1]
Bonjour,
J'aurais voulus savoir si le bundle est disponible pour la version de symfony définit dans le titre.
Cordialement

**Comment by comstep** [comment]
Salut MWJordanP,

Tu as essayé de faire la méthode d'installation via composer et ça ne fonctionne pas ?
C'est vrai que dans le titre du bundle j'ai mis Symfony2 mais il se peut qu'il marche sur le 3 également, n'ayant pas encore essayé le 3 je ne saurais le dire pour l'instant.

Si jamais tu testes merci de faire ton retour, ça serait cool d'avoir l'info.

**Comment by bnbc** [comment]
Salut MWJordanP,

Tu as essayé de faire la méthode d'installation via composer et ça ne fonctionne pas ?
C'est vrai que dans le titre du bundle j'ai mis Symfony2 mais il se peut qu'il marche sur le 3 également, n'ayant pas encore essayé le 3 je ne saurais le dire pour l'instant.

Si jamais tu testes merci de faire ton retour, ça serait cool d'avoir l'info.

**Comment by MWJordanP** [comment]
J'ai voulus le faire, dans ton composer.json tu ne spécifie pas symfony 3.* donc celui-ci n'est pas disponible pour ton bundle malheureusement. D’où mon intervention, il doit y avoir quelques modifications à réaliser sur ton bundle.
De mon côté j'avais décidé de faire un fork de ton bundle et voir comment il réagis sur symfony 3 sauf que quand je l'ai mis en tant que champs dans mon formulaire tout me paraissais bon sauf à la validation  du formulaire une erreur apparaissais donc comment de ton côté enregistre tu en BDD l'image upload en ajax ? 
Car actuellement tu explique la manière dont fonctionne le formulaire et les configurations mais pas comment récupérer celui-ci en BDD.
Merci à toi par avance

**Comment by bnbc** [comment]
Logiquement si ton formulaire est associé à une entité, le nom du fichier uploadé devrait se mettre dans le champs auquel tu associes l'upload ajax (un champs texte)
Sinon c'est à toi de gérer l'enregistrement en BDD + le déplacement du fichier car le bundle ne le fait pas, il assigne juste au champs caché (qui porte le nom que tu as mis dans ton form) le nom du fichier uploadé.

**Comment by MWJordanP** [comment]
Pas de soucis la dessus, aurais tu un exemple ? pour que d'autre puisse bien cerner l'utilisation si possible ?
Merci à toi, de mon côté j'ai fait le changement du moins le minimum pour symfony 3 mais je n'ai pas accées au Push sur le projet

**Comment by bnbc** [comment]
Oui j'expliquerais mieux cette partie dans le README dès que j'ai un peu de temps.
Je n'ai pas accès à ton lien plus haut. Que faut-il faire pour que tu puisses faire un push ? je suis novice sur l’utilisation de github et la notion de fork.

**Comment by MWJordanP** [comment]
Je test demain pour voir si le bundle dois subir d'autre modification, j'attend ton avis sur la compatibilité avec SF2

**Comment by Legenyes** [comment]
Ce projet m'interesse aussi sous sf3.1

**Comment by bnbc** [comment]
Les modifications apportées par MWJordanP pour SF3 ont été incluses, de mon coté le fonctionnement pour SF2 est validé. Donc on est bon :) Merci à toi MWJordanP.

**Comment by Legenyes** [comment]
Visiblement **JMSTranslationBundle** est obligatoire pour ce bundle, Dommage

Sinon voici une première liste de remarque me concernant
```
# app/config/config.yml

twig:
    form:
        resources:
            - BnbcUploadBundle:Form:fields.html.twig

```
A remplacer par 
```
# app/config/config.yml

twig:
    form_themes:
            - BnbcUploadBundle:Form:fields.html.twig
```

`$formBuilder->add('myfield', 'bnbc_ajax_file');`
A remplacer par 
`$formBuilder->add('myfield', AjaxfileType::class);`

```
<script src="{{ asset('bundles/bnbc/upload/1_jquery.min.js') }}"></script>
<script src="{{ asset('bundles/bnbc/upload/2_jquery.ui.widget.js') }}"></script>
<script src="{{ asset('bundles/bnbc/upload/3_jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('bundles/bnbc/upload/4_jquery.fileupload.js') }}"></script>
<script src="{{ asset('bundles/bnbc/upload/5_init.js') }}"></script>
```

a remplacer par 

```
<script src="{{ asset('bundles/bnbcupload/js/1_jquery.min.js') }}"></script>
<script src="{{ asset('bundles/bnbcupload/js/2_jquery.ui.widget.js') }}"></script>
<script src="{{ asset('bundles/bnbcupload/js/3_jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('bundles/bnbcupload/js/4_jquery.fileupload.js') }}"></script>
<script src="{{ asset('bundles/bnbcupload/js/5_init.js') }}"></script>
```

Et j'ai pour le moment un bug sur `if($request->isXmlHttpRequest()){}` qui me retourn toujours false lors de la soumission de mon image

**Comment by MWJordanP** [comment]
Merci de ta réponse je vais dés que possible corriger cela de mon côté dés que j'en ai la possibilité
