### ISSUE TITLE
The "replace" filter expects an array or "Traversable" as replace values, got "string".

### ISSUE THREAD

**Issue by Nowwis** [bnbc/Symfony-Upload-Ajax#11]
Bonjour,

Soucis aujourd'hui sur le module en version Symfony 3.3.10

J'ai modifié la ligne Resources/views/Form/fields.html.twig : 
input type="hidden" value="{{ value }}" name="{{ id }}_{{ varName }}" id="{{ id }}_{{ varName|replace('[', '-')|replace(']', '-') }}"

Par : 
input type="hidden" value="{{ value }}" name="{{ id }}_{{ varName }}" id="{{ id }}_{{ varName|replace({'[': '-'})|replace({'[': '-'}) }}"

Tout fonctionne de mon côté, si ça peut aider.

**Comment by bnbc** [comment]
Ok merci j'ai inclus ta modif, elle marche aussi en Symfony 2.
