### ISSUE TITLE
ERROR - A non well formed numeric value encountered

### ISSUE THREAD

**Issue by Legenyes** [bnbc/Symfony-Upload-Ajax#12]
Getting the following error when upload a picture.

> A non well formed numeric value encountered
in vendor/bnbc/upload-bundle/Bnbc/UploadBundle/BlueImp/UploadHandler.php (line 355)

config : 
PHP 7.1.11-1+
Symfony 3.3.12

**Comment by bnbc** [comment]
Thks!
