### ISSUE TITLE
Erreur de validation

### ISSUE THREAD

**Issue by Legenyes** [bnbc/Symfony-Upload-Ajax#5]
J'obtient une erreur lors de la soumission du formulaire.
Errer lié aux contrainte sur le champ original.

Dès lors je me demandais pourquoi avoir fais cela `{{ block('hidden_widget') }}` dans le _fields.html.twig_  ??
Quand je l’enlevé, je n'ai plus d'erreurs

**Comment by bnbc** [comment]
Sauf que du coup tu n'as plus le champs caché dans lequel vient s'inscrire le nom du fichier uploadé si ?
Pour éviter les blocages sur la soumission sur un de mes projets j'ai ajouté  `compound' => false` : 
`->add('image1', 'bnbc_ajax_file', array('dropZone' => false, 'progressBar' => true, 'compound' => false))`

**Comment by Legenyes** [comment]
thans !

**Comment by wbcreation** [comment]
Bonjour,

Je rencontre un problème, lors de la validation du formulaire, le formulaire m'indique que le fichier est introuvable. Par contre l'upload sur le serveur se fait bien.

Voici la déclaration de mon formulaire : 
`
                $message = new Messages();
                $message->setDate(new \DateTime("UTC"));
                $form = $this->createFormBuilder($message)
                    ->add('message', TextareaType::class)
                    ->add('groupe', TextType::class, array(
                        'label' => 'form.categorie',
                        'translation_domain' => 'FOSUserBundle',
                        'attr' => array(
                            'class' => 'ms autocompleteone')))
                    ->add('photo', 'bnbc_ajax_file', array(
                        'label' => 'Photo',
                        'required' => false,
                        'attr' => array('class' => 'input-file'),
                        'progressBar' => true,
                        'dropZone'  => false,
                        'compound' => false
                    ))
                    ->add('tag', TextType::class, array(
                        'label' => 'form.tag',
                        'translation_domain' => 'FOSUserBundle',
                        'attr' => array(
                            'class' => 'ms autocompletetwo')))
                    ->getForm();
                $form->handleRequest($request);`

Avez-vous une idée d'où vient le problème ? 

Mercu
