### ISSUE TITLE
Translation require jms

### ISSUE THREAD

**Issue by Beninho** [bnbc/Symfony-Upload-Ajax#6]
Hello,
Thanks to sharing your source code !
I have some problems with your bundle.
Log trace : 

[Symfony\Component\Translation\Exception\InvalidResourceException]                                    
  Invalid resource provided: "1.2"; Errors: [ERROR 1845] Element '{urn:jms:translation}reference-file'  
  : No matching global element declaration available, but demanded by the strict wildcard. (in /var/ww  
  w/symfony/ - line 12, column 0) 
...

I've resolved it adding dependency with "jms/translation-bundle".

**Comment by Alphega** [comment]
Hi !
Indeed this bundle is require !
My problem actually is the fact that i'm working on SF 3.1 and JMS isn't up to date at the moment and don't work on it... Is there a solution for by pass this ?
![image](https://cloud.githubusercontent.com/assets/7330755/23747534/4ff0a404-04c0-11e7-9a30-da191e77fb96.png)
I'm currently getting this error... If someone have already met this problem i'll be so happy !
Thanks for all !

**Comment by bnbc** [comment]
Hello, try to remove all jms ref in vendor\bnbc\upload-bundle\Bnbc\UploadBundle\Resources\translations\messages.fr.xliff : 
- xmlns:jms="urn:jms:translation"
- and all <jms:reference-file line="74">....</jms:reference-file>

Maybe after that the bundle no need jms.
If it works say me, i'll fixed it soon as possible
