### ISSUE TITLE
Bootstrap progress bar

### ISSUE THREAD

**Issue by anybug** [bnbc/Symfony-Upload-Ajax#8]
slt BNBC,

tout d'abord merci pour ton travail. 
Juste pour info, la barre de progression n'apparaît pas automatiquement par défaut. Dans un projet utilisant bootstrap (comme le mien), il suffit d'ajouter la classe progress-bar à la variable progress (ligne 69):

`progress = $('<div/>').attr('id', '{{ id }}_progress').addClass('bnbc-ajax-file-progress');`

devient:

`progress = $('<div/>').attr('id', '{{ id }}_progress').addClass('bnbc-ajax-file-progress progress-bar');`

**Comment by bnbc** [comment]
Tu as désormais un paramètre progressBarClass pour définir la/les classe(s) de la progressBar.
