### ISSUE TITLE
Exception Array to string conversion at line

### ISSUE THREAD

**Issue by anybug** [bnbc/Symfony-Upload-Ajax#9]
On rencontre 2 erreurs de Array to String conversion si on met dans le formType l'option 'image_versions'.

Dans BnbcUploadBundle:Form:fields.html.twig, le script fait une boucle sur les valeurs du formData mais ne prend pas en charge les valeurs de type tableau. Il faut donc considérer que chaque valeur peut être un tableau. Voilà comment je m'en suis sorti pour l'instant pour une itération sur 3 niveaux, c'est bien-sûr  temporaire et à améliorer (en faisant un include d'un sous-template par exemple):

ligne 7, remplacer:
```
{% for name, val in form.vars.formData %}
          {% if val %}
                <input type="hidden" value="{{ val }}" name="{{ id }}_{{ name }}" id="{{ id }}_{{ name }}" />
          {% endif %}
{% endfor %}
```
par:
```
{% for name, val in form.vars.formData %}
	{% if val %}
		{% if val is iterable %}
			{% for subname, subval in val %}
				{% if subval %}
					{% if subval is iterable %}
						{% for subsubname, subsubval in subval %}
							{% if subsubval %}
								<input type="hidden" value="{{ subsubval }}" name="{{ id }}_{{ name }}[{{ subname }}][{{ subsubname }}]" id="{{ id }}_{{ name }}_{{ subname }}_{{ subsubname }}" />
							{% endif %}
						{% endfor %}
					{% else %}
					<input type="hidden" value="{{ subval }}" name="{{ id }}_{{ name }}[{{ subname }}]" id="{{ id }}_{{ name }}_{{ subname }}" />
					{% endif %}
				{% endif %}
			{% endfor %}
		{% else %}
			<input type="hidden" value="{{ val }}" name="{{ id }}_{{ name }}" id="{{ id }}_{{ name }}" />
		{% endif %}
	{% endif %}
{% endfor %}
```

Idem ligne 32, remplacer:
```
{% for name, value in form.vars.formData %}
                {% if value %}
                    {{ id }}_formData.push({'name': '{{ name }}', value: '{{ value }}'});
                {% endif %}
{% endfor %}
```
par:
```
{% for name, value in form.vars.formData %}
    {% if value %}
        {% if value is iterable %}
            {% for subname, subval in value %}
                {% if subval %}
                    {% if subval is iterable %}
                        {% for subsubname, subsubval in subval %}
                            {% if subsubval %}
                                {{ id }}_formData.push({'name': '{{ name }}[{{ subname }}][{{ subsubname }}]', value: '{{ subsubval }}'});
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {{ id }}_formData.push({'name': '{{ name }}[{{ subname }}]', value: '{{ subval }}'});
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% else %}
            {{ id }}_formData.push({'name': '{{ name }}', value: '{{ value }}'});
        {% endif %}
    {% endif %}
{% endfor %}
```

**Comment by Tofandel** [comment]
Pourquoi ne pas juste créer une macro recursive ?

**Comment by anybug** [comment]
notre solution était temporaire, on devait la factoriser plus tard mais on ne l'a toujours pas fait... 
Merci pour ta solution on va la tester ;)

**Comment by bnbc** [comment]
La macro récursive est en place.
Merci Tofandel pour la piste !

**Comment by daconrilcy** [comment]
Bonjour,
J'ai découvert depuis peu votre Bundle qui m’intéresse au plus haut point !
Je développe depuis peu sous Symfony et du coup j'en maîtrise encore peu les arcanes.
J'essaie de faire fonctionner votre bundle mais je rencontre malheureusement un problème similaire à celui décrit ci dessus. J'ai ce message d'erreur de Symfony à l'affichage de la page 
The "replace" filter expects an array or "Traversable" as replace values, got "string".
Je me demande si je ne fais pas une erreur dans l'intégration de la form au sein de Twig ? Il n'y a  pas d'explication sur ce point dans votre doc ... Ça pourrait m'être très utile !
En vous remerciant,
